language: node_js
node_js:
- stable
install:
- yarn
script:
- yarn test
- yarn build
deploy:
  provider: heroku
  app: dynastyhub-api
  api_key:
    secure: cLnHKFW2fUa6UVraBxZbn+TTclHlHESdRGZ5Bv1ipJH0H1bemQbxUw5cnGdWUuXgBTrCxLADZqdRxiU/1DwVMZ6U1O0zOB+yBVRJIqkim0jGN8zlewaQtmzLMIy4zUURZUpwpIQh12+KDGPLp5f6wbahMoTxrhaMQP5vllcxHkyq6t4Y0JpK3lrgICtVV2LR0OlmQVcqpeXw2cVuCiek2I0+kOMSV5lAN7PX4DdNeQ3JuVSw7sAIoVvu7uhMTspaMnmJcgfI/Ait/F0ddTfVto13uYxBP3DZCMgMBbAF8RDf6XQi/N24FLMGgWcuX+sh1LBJ7sEjW4corWGL3vUMQMp6EuDdyETZJLbEO+DSTB2ocKmHBSnSaL0q3Yrc+rtuGUBE7wc3Dlb6WH+O2FPjxgezbNoJTXgIwwkDHnrRK+2Stw8kYc2ER+ZDPmBcsxyXW8AT5YmyQNMnLFndV+Y13hf2J5836n4Erk/wrkpZw2RpwbhHVNMxdHFFrdteS93PxZeVd0fsuNbpKtRkM6Cj6Kvf7dIvkroHBDWJed1hjHcRea1VCsgBqPtozvBXh2w2a/mvPLkUc1+4A0qV1Zh2/OtekP44r0O0KfbxfdfLRvygL9zYZCjCZQXjNYMax1nXmgLRaIZAJeSbLXsbVZDJ7528jDdNH0mKzz3F4TpwUnY=
  skip_cleanup: true
